name: "WCW Nitro (menu overlay)"
sha1: 34afaeb6fdcd909ffbaa813ac16d40ebba55217c
options:
  basename: wmenu.bin
  target_path: disc/WMENU.BIN
  base_path: ../
  platform: psx
  compiler: PSYQ

  asm_path: asm/wmenu
  src_path: src/wmenu
  build_path: build/

  ld_script_path: linker/wmenu.ld

  find_file_boundaries: False
  gp_value: 0x80054c60
  global_vram_start: 0x80010000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/symbol_addrs.wmenu.txt
    - config/symbol_addrs.slus_003.97.txt
  reloc_addrs_path:
    - configs/reloc_addrs.wmenu.txt

  undefined_funcs_auto_path: linker/undefined_funcs_auto.wmenu.txt
  undefined_syms_auto_path: linker/undefined_syms_auto.wmenu.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: wmenu
    type: code
    start: 0x0
    align: 4
    subalign: 4
    vram: 0x80065ee4
    subsegments:
      - [0x0, rodata]
      - [0xA20, asm] # start of WMENU overlay functions
      - [0x22F4, asm, card] # WMENU overlay card-related functions
      - [0x3018, asm] # WMENU overlay functions continue
      - [0x44B8, asm, main] # WMENU overlay main function
      - [0xF3F8, asm] # WMENU overlay functions continue
      - [0xFE64, data] # WMENU overlay functions end
  - [0x14cf34]
